controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # franka_robot_state_broadcaster:
    #   type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
    
    # franka_robot_model_broadcaster:
    #   type: franka_robot_state_broadcaster/FrankaRobotModelBroadcaster

    single_multi_mode_controller:
      type: multi_mode_controller/SingleMultiModeController

# franka_robot_state_broadcaster:
#   ros__parameters:
#     arm_id: panda

# franka_robot_model_broadcaster:
#   ros__parameters:
#     arm_id: panda
    
single_multi_mode_controller:
  ros__parameters:
    arm_count: 2
    arm_1:
      arm_id: left
    arm_2:
      arm_id: right
    controllers: ["panda_joint_impedance_controller", 
                  "comless_coupled_dual_cartesian_impedance_controller", 
                  "dual_cartesian_impedance_controller",
                  "des_coupled_dual_cartesian_impedance_controller"]
    resources:
        comless_coupled_dual_cartesian_impedance_controller: ["left&right"]
        dual_cartesian_impedance_controller: ["left&right"]
        des_coupled_dual_cartesian_impedance_controller: ["left&right"]
        panda_joint_impedance_controller: ["left","right"]
    start_controllers:
        names: ["dual_cartesian_impedance_controller"]
        resources:
            dual_cartesian_impedance_controller: ["left&right"]