controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_impedance_example_controller:
      type: franka_example_controllers/JointImpedanceExampleController

    cartesian_impedance_example_controller:
      type: franka_example_controllers/CartesianImpedanceExampleController

    joint_velocity_example_controller:
      type: franka_example_controllers/JointVelocityExampleController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

    model_example_controller:
      type: franka_example_controllers/ModelExampleController
    

franka_robot_state_broadcaster:
  ros__parameters:
    arm_id: panda

joint_impedance_example_controller:
  ros__parameters:
    arm_id: panda
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5

cartesian_impedance_example_controller:
  ros__parameters:
    arm_id: panda

joint_velocity_example_controller:
  ros__parameters:
    arm_id: panda
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5

model_example_controller:
  ros__parameters:
    arm_id: panda